language: python
python:
  - "2.7"
install:
  - pip install -r requirements.pip --use-mirrors
  - pip install -r requirements-test.pip --use-mirrors
script: cd pybamboo && nosetests
notifications:
  irc: "irc.freenode.org#moditest"
